### ISSUE TITLE
Add option to disable sort

### ISSUE THREAD

**Issue by QuingKhaos** [rafeca/prettyjson#24]
May you add a option to disable the sorting of the numeric object keys?

Example:

```
{
    "4": 6,
    "B": 1,
    "F": 9,
    "8": 4,
    "I": 3,
    "2": 13,
    "3": 7,
    "9": 13,
    "6": 19,
    "D": 6,
    "7": 2,
    "A": 1,
    "G": 3,
    "5": 4,
    "E": 3
}
```

results in

```
2: 13
3: 7
4: 6
5: 4
6: 19
7: 2
8: 4
9: 13
B: 1
F: 9
I: 3
D: 6
A: 1
G: 3
E: 3
```

**Comment by rafeca** [comment]
Hey! The sorting is automatically done by the `JSON.parse()` API, so I would need to do big changes on the internals of the lib in order to be able to fix this (see https://github.com/rafeca/prettyjson/pull/26).

In the short-term I'm not planning to do big changes in the library, but I'll keep the task opened in case I have some time to think about a solution here

**Comment by rafeca** [comment]
Hey there, after some consideration I'm closing this issue: this is part of the standard way of sorting keys in JS so changing it would first be a complex and also it would go against JS standards.

Thanks anyways for the suggestion
